### ISSUE TITLE
Google Fonts blocked on ultimate and unified packs

### ISSUE THREAD

**Issue by mrbluecoat** [EnergizedProtection/Energized_Linux#1]
FYI, fonts.googleapis.com and fonts.gstatic.com are blocked when using ultimate or unified packs (porn and smaller packs are fine).  Test case with Brave browser on Lubuntu 18.10: load https://fonts.google.com/ and font samples don't appear and shortly thereafter site says something went wrong.

**Comment by AvinashReddy3108** [comment]
That was a hosts entry issue, nothing related to the script..
